import type {
  NeighborhoodLookupResponse,
  NeighborhoodSuggestion,
  RegionDirection,
  RegionSummary,
} from './neighborhood-contract';
import type { ZoneGridResult } from './zone-contract';
import { classifyRegion, REGION_LABELS, REGION_ORDER } from './zone-regions';

// Directional labels generated by zone-grid when no named place is nearby.
// They describe grid positions, not real neighborhoods, so they are excluded.
const DIRECTIONAL_FALLBACK_LABELS = new Set([
  'SW Quadrant',
  'South',
  'SE Quadrant',
  'West',
  'Central',
  'East',
  'NW Quadrant',
  'North',
  'NE Quadrant',
  'Zone',
]);

interface RegionStats {
  zoneCount: number;
  topZone: NeighborhoodSuggestion;
}

function buildRegionSummaries(zones: readonly NeighborhoodSuggestion[]): RegionSummary[] {
  const statsByRegion = new Map<RegionDirection, RegionStats>();

  for (const zone of zones) {
    const current = statsByRegion.get(zone.region);
    if (!current) {
      statsByRegion.set(zone.region, { zoneCount: 1, topZone: zone });
      continue;
    }

    current.zoneCount += 1;
    if (zone.score > current.topZone.score) {
      current.topZone = zone;
    }
  }

  return REGION_ORDER.map((direction) => {
    const stats = statsByRegion.get(direction);
    return {
      direction,
      label: REGION_LABELS[direction],
      score: stats?.topZone.score ?? 0,
      zoneCount: stats?.zoneCount ?? 0,
      topLabel: stats?.topZone.label ?? null,
    };
  });
}

export function buildNeighborhoodLookup(zoneGrid: ZoneGridResult): NeighborhoodLookupResponse {
  const zones: NeighborhoodSuggestion[] = zoneGrid.zones
    .filter(
      (zone) =>
        !DIRECTIONAL_FALLBACK_LABELS.has(zone.label) && zone.score > 0 && zone.amenities.total > 0
    )
    .map((zone) => ({
      label: zone.label,
      score: zone.score,
      wealthScore: zone.wealthScore,
      businessScore: zone.businessScore,
      archetype: zone.archetype,
      level: zone.level,
      latitude: zone.latitude,
      longitude: zone.longitude,
      region: zoneGrid.singleZone
        ? 'central'
        : classifyRegion(zone.latitude, zone.longitude, zoneGrid.bbox),
    }));

  return {
    regions: buildRegionSummaries(zones),
    zones,
    singleZone: zoneGrid.singleZone,
  };
}
