#!/bin/bash

# ===========================================
# Lead Snatcher - First Time Setup Script
# ===========================================
# This script handles everything needed to get started:
# 1. Check prerequisites
# 2. Install dependencies
# 3. Generate environment file with secrets
# 4. Setup database (SQLite or PostgreSQL)
# 5. Create first user
# ===========================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

print_step() {
    echo -e "\n${BLUE}==>${NC} $1"
}

print_success() {
    echo -e "${GREEN}✓${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

print_error() {
    echo -e "${RED}✗${NC} $1"
}

# Generate a random secret
generate_secret() {
    openssl rand -base64 32 2>/dev/null || head -c 32 /dev/urandom | base64
}

echo ""
echo ""
echo " _                    _   ____              _       _               "
echo "| |    ___  __ _  ___| | / ___| _ __   __ _| |_ ___| |__   ___ _ __ "
echo "| |   / _ \/ _\` |/ _ \\ | \\___ \\| '_ \\ / _\` | __/ __| '_ \\ / _ \\ '__|"
echo "| |__|  __/ (_| | (_) | |  ___) | | | | (_| | || (__| | | |  __/ |   "
echo "|_____\\___|\\__,_|\\___/|_| |____/|_| |_|\\__,_|\\__\\___|_| |_|\\___|_|   "
echo ""
echo "Lead Generation CRM - Setup"
echo "============================"

# ===========================================
# Step 1: Check Prerequisites
# ===========================================
print_step "Checking prerequisites..."

# Check Node.js
if ! command -v node &> /dev/null; then
    print_error "Node.js is not installed. Please install Node.js 18+ first."
    exit 1
fi

NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
if [ "$NODE_VERSION" -lt 18 ]; then
    print_error "Node.js 18+ required. You have $(node -v)"
    exit 1
fi
print_success "Node.js $(node -v)"

# Check npm
if ! command -v npm &> /dev/null; then
    print_error "npm is not installed."
    exit 1
fi
print_success "npm $(npm -v)"


# ===========================================
# Step 2: Install Dependencies
# ===========================================
print_step "Installing dependencies..."

npm install --silent
print_success "Dependencies installed"

# ===========================================
# Step 3: Database Setup (SQLite)
# ===========================================
print_step "Configuring SQLite database..."

# ===========================================
# Step 4: Generate Environment File
# ===========================================
print_step "Generating environment file..."

if [ -f .env ]; then
    print_warning ".env already exists"
    read -p "Overwrite? [y/N]: " OVERWRITE
    if [ "$OVERWRITE" != "y" ] && [ "$OVERWRITE" != "Y" ]; then
        print_warning "Keeping existing .env"
    else
        rm .env
    fi
fi

if [ ! -f .env ]; then
    # Generate secrets
    NEXTAUTH_SECRET=$(generate_secret)
    ADMIN_SECRET=$(generate_secret)
    ENCRYPTION_SECRET=$(generate_secret)
    ENCRYPTION_SALT=$(openssl rand -base64 16 2>/dev/null || head -c 16 /dev/urandom | base64)

    # SQLite database
    DATABASE_URL="file:./data/lead-snatcher.db"

    cat > .env << EOF
# ===========================================
# Lead Snatcher Environment Configuration
# Generated by setup script on $(date)
# ===========================================

# Database (SQLite)
DATABASE_URL="${DATABASE_URL}"

# NextAuth
NEXTAUTH_SECRET="${NEXTAUTH_SECRET}"
NEXTAUTH_URL="http://localhost:3000"

# Admin Secret - for creating users via /admin
ADMIN_SECRET="${ADMIN_SECRET}"

# Encryption Secret - for API key storage
ENCRYPTION_SECRET="${ENCRYPTION_SECRET}"
ENCRYPTION_SALT="${ENCRYPTION_SALT}"

# ===========================================
# Optional: External APIs
# ===========================================
# RAPIDAPI_KEY="your-rapidapi-key"
EOF

    print_success "Environment file created with auto-generated secrets"
fi

# ===========================================
# Step 5: Setup Database
# ===========================================
print_step "Setting up database..."

# Create data directory for SQLite
mkdir -p data
print_success "SQLite data directory created"

# Generate Prisma client and run migrations
print_step "Running database migrations..."
npm run db:generate --silent
npm run db:push --silent 2>/dev/null || npm run db:migrate --silent
print_success "Database schema applied"

# ===========================================
# Step 6: Create Default User
# ===========================================
print_step "Creating default admin user..."

# Generate a secure random password for the admin user
ADMIN_PASSWORD=$(openssl rand -base64 18)

# Create default user via tsx (ESM compatible)
ADMIN_PASSWORD="$ADMIN_PASSWORD" npx tsx -e "
import path from 'node:path';
import crypto from 'node:crypto';
import { PrismaClient } from './src/generated/prisma/client.js';
import { PrismaBetterSqlite3 } from '@prisma/adapter-better-sqlite3';
import bcrypt from 'bcrypt';

const dbPath = path.join(process.cwd(), 'data', 'lead-snatcher.db');
const adapter = new PrismaBetterSqlite3({ url: dbPath });
const prisma = new PrismaClient({ adapter });

async function createDefaultUser() {
  try {
    const existing = await prisma.user.findUnique({ where: { email: 'admin@leadsnatcher.local' } });
    if (!existing) {
      const password = process.env.ADMIN_PASSWORD;
      const hash = await bcrypt.hash(password, 12);
      await prisma.user.create({
        data: {
          email: 'admin@leadsnatcher.local',
          name: 'Admin',
          password: hash,
          createdAt: new Date()
        }
      });
      console.log('created');
    } else {
      console.log('exists');
    }
  } finally {
    await prisma.\$disconnect();
  }
}
createDefaultUser();
" 2>/dev/null && print_success "Default user created" || print_warning "Could not create default user"

# ===========================================
# Done!
# ===========================================
echo ""
echo -e "${GREEN}=========================================${NC}"
echo -e "${GREEN}  Setup Complete!${NC}"
echo -e "${GREEN}=========================================${NC}"
echo ""
echo "Start the development server:"
echo -e "  ${BLUE}npm run dev${NC}"
echo ""
echo "Then open: http://localhost:3000"
echo ""
echo -e "${YELLOW}Default Login:${NC}"
echo "  Email:    admin@leadsnatcher.local"
echo "  Password: $ADMIN_PASSWORD"
echo ""
echo -e "${RED}⚠ CHANGE THIS PASSWORD IMMEDIATELY after first login.${NC}"
echo ""

echo "Database: SQLite (data/lead-snatcher.db)"

echo ""
echo "Useful commands:"
echo "  npm run db:studio  - Open database GUI"
echo "  npm run setup:user - Create/update users"
echo ""
